// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client';
import { client } from './client.gen';
import type {
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostData,
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostErrors,
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponses,
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostData,
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostErrors,
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponses,
  CreateCourtApiTournamentsTournamentIdCourtsPostData,
  CreateCourtApiTournamentsTournamentIdCourtsPostErrors,
  CreateCourtApiTournamentsTournamentIdCourtsPostResponses,
  CreateMatchApiTournamentsTournamentIdMatchesPostData,
  CreateMatchApiTournamentsTournamentIdMatchesPostErrors,
  CreateMatchApiTournamentsTournamentIdMatchesPostResponses,
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostData,
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostErrors,
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponses,
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostData,
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostErrors,
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponses,
  CreateNewClubApiClubsPostData,
  CreateNewClubApiClubsPostErrors,
  CreateNewClubApiClubsPostResponses,
  CreateRankingApiTournamentsTournamentIdRankingsPostData,
  CreateRankingApiTournamentsTournamentIdRankingsPostErrors,
  CreateRankingApiTournamentsTournamentIdRankingsPostResponses,
  CreateRoundApiTournamentsTournamentIdRoundsPostData,
  CreateRoundApiTournamentsTournamentIdRoundsPostErrors,
  CreateRoundApiTournamentsTournamentIdRoundsPostResponses,
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostData,
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostErrors,
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponses,
  CreateStageApiTournamentsTournamentIdStagesPostData,
  CreateStageApiTournamentsTournamentIdStagesPostErrors,
  CreateStageApiTournamentsTournamentIdStagesPostResponses,
  CreateStageItemApiTournamentsTournamentIdStageItemsPostData,
  CreateStageItemApiTournamentsTournamentIdStageItemsPostErrors,
  CreateStageItemApiTournamentsTournamentIdStageItemsPostResponses,
  CreateTeamApiTournamentsTournamentIdTeamsPostData,
  CreateTeamApiTournamentsTournamentIdTeamsPostErrors,
  CreateTeamApiTournamentsTournamentIdTeamsPostResponses,
  CreateTournamentApiTournamentsPostData,
  CreateTournamentApiTournamentsPostErrors,
  CreateTournamentApiTournamentsPostResponses,
  DeleteClubApiClubsClubIdDeleteData,
  DeleteClubApiClubsClubIdDeleteErrors,
  DeleteClubApiClubsClubIdDeleteResponses,
  DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteData,
  DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteErrors,
  DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteResponses,
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteData,
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteErrors,
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponses,
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteData,
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteData,
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteErrors,
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponses,
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteData,
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteErrors,
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponses,
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteData,
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteErrors,
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponses,
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteData,
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteData,
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteErrors,
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponses,
  DeleteTournamentApiTournamentsTournamentIdDeleteData,
  DeleteTournamentApiTournamentsTournamentIdDeleteErrors,
  DeleteTournamentApiTournamentsTournamentIdDeleteResponses,
  FrontendFullPathGetData,
  FrontendFullPathGetErrors,
  FrontendFullPathGetResponses,
  GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetData,
  GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetErrors,
  GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponses,
  GetClubsApiClubsGetData,
  GetClubsApiClubsGetResponses,
  GetCourtsApiTournamentsTournamentIdCourtsGetData,
  GetCourtsApiTournamentsTournamentIdCourtsGetErrors,
  GetCourtsApiTournamentsTournamentIdCourtsGetResponses,
  GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetData,
  GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors,
  GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses,
  GetMeApiUsersUserIdGetData,
  GetMeApiUsersUserIdGetErrors,
  GetMeApiUsersUserIdGetResponses,
  GetMetricsApiMetricsGetData,
  GetMetricsApiMetricsGetResponses,
  GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetData,
  GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetErrors,
  GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponses,
  GetPlayersApiTournamentsTournamentIdPlayersGetData,
  GetPlayersApiTournamentsTournamentIdPlayersGetErrors,
  GetPlayersApiTournamentsTournamentIdPlayersGetResponses,
  GetRankingsApiTournamentsTournamentIdRankingsGetData,
  GetRankingsApiTournamentsTournamentIdRankingsGetErrors,
  GetRankingsApiTournamentsTournamentIdRankingsGetResponses,
  GetStagesApiTournamentsTournamentIdStagesGetData,
  GetStagesApiTournamentsTournamentIdStagesGetErrors,
  GetStagesApiTournamentsTournamentIdStagesGetResponses,
  GetTeamsApiTournamentsTournamentIdTeamsGetData,
  GetTeamsApiTournamentsTournamentIdTeamsGetErrors,
  GetTeamsApiTournamentsTournamentIdTeamsGetResponses,
  GetTournamentApiTournamentsTournamentIdGetData,
  GetTournamentApiTournamentsTournamentIdGetErrors,
  GetTournamentApiTournamentsTournamentIdGetResponses,
  GetTournamentsApiTournamentsGetData,
  GetTournamentsApiTournamentsGetErrors,
  GetTournamentsApiTournamentsGetResponses,
  GetUserApiUsersMeGetData,
  GetUserApiUsersMeGetResponses,
  LoginForAccessTokenApiTokenPostData,
  LoginForAccessTokenApiTokenPostErrors,
  LoginForAccessTokenApiTokenPostResponses,
  PingApiPingGetData,
  PingApiPingGetResponses,
  PutUserPasswordApiUsersUserIdPasswordPutData,
  PutUserPasswordApiUsersUserIdPasswordPutErrors,
  PutUserPasswordApiUsersUserIdPasswordPutResponses,
  ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostData,
  ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostErrors,
  ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostResponses,
  RegisterDemoUserApiUsersRegisterDemoPostData,
  RegisterDemoUserApiUsersRegisterDemoPostErrors,
  RegisterDemoUserApiUsersRegisterDemoPostResponses,
  RegisterUserApiUsersRegisterPostData,
  RegisterUserApiUsersRegisterPostErrors,
  RegisterUserApiUsersRegisterPostResponses,
  RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostData,
  RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
  RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostData,
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostErrors,
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponses,
  StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostData,
  StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors,
  StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses,
  UpdateClubApiClubsClubIdPutData,
  UpdateClubApiClubsClubIdPutErrors,
  UpdateClubApiClubsClubIdPutResponses,
  UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutData,
  UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutErrors,
  UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutResponses,
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutData,
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutErrors,
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponses,
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutData,
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutErrors,
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponses,
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutData,
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutErrors,
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponses,
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutData,
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutErrors,
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponses,
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutData,
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutErrors,
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponses,
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutData,
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutErrors,
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponses,
  UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
  UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
  UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutData,
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutErrors,
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponses,
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostData,
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
  UpdateTournamentByIdApiTournamentsTournamentIdPutData,
  UpdateTournamentByIdApiTournamentsTournamentIdPutErrors,
  UpdateTournamentByIdApiTournamentsTournamentIdPutResponses,
  UpdateUserDetailsApiUsersUserIdPutData,
  UpdateUserDetailsApiUsersUserIdPutErrors,
  UpdateUserDetailsApiUsersUserIdPutResponses,
  UploadLogoApiTournamentsTournamentIdLogoPostData,
  UploadLogoApiTournamentsTournamentIdLogoPostErrors,
  UploadLogoApiTournamentsTournamentIdLogoPostResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Clubs
 */
export const getClubsApiClubsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetClubsApiClubsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetClubsApiClubsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/clubs',
    ...options,
  });

/**
 * Create New Club
 */
export const createNewClubApiClubsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateNewClubApiClubsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNewClubApiClubsPostResponses,
    CreateNewClubApiClubsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/clubs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Club
 */
export const deleteClubApiClubsClubIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteClubApiClubsClubIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteClubApiClubsClubIdDeleteResponses,
    DeleteClubApiClubsClubIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/clubs/{club_id}',
    ...options,
  });

/**
 * Update Club
 */
export const updateClubApiClubsClubIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateClubApiClubsClubIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateClubApiClubsClubIdPutResponses,
    UpdateClubApiClubsClubIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/clubs/{club_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Metrics
 */
export const getMetricsApiMetricsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMetricsApiMetricsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetMetricsApiMetricsGetResponses, unknown, ThrowOnError>({
    responseType: 'text',
    url: '/api/metrics',
    ...options,
  });

/**
 * Healthcheck ping
 */
export const pingApiPingGet = <ThrowOnError extends boolean = false>(
  options?: Options<PingApiPingGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<PingApiPingGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/ping',
    ...options,
  });

/**
 * Login For Access Token
 */
export const loginForAccessTokenApiTokenPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginForAccessTokenApiTokenPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    LoginForAccessTokenApiTokenPostResponses,
    LoginForAccessTokenApiTokenPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/api/token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  });

/**
 * Get Tournaments
 */
export const getTournamentsApiTournamentsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTournamentsApiTournamentsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetTournamentsApiTournamentsGetResponses,
    GetTournamentsApiTournamentsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments',
    ...options,
  });

/**
 * Create Tournament
 */
export const createTournamentApiTournamentsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTournamentApiTournamentsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateTournamentApiTournamentsPostResponses,
    CreateTournamentApiTournamentsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Tournament
 */
export const deleteTournamentApiTournamentsTournamentIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTournamentApiTournamentsTournamentIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteTournamentApiTournamentsTournamentIdDeleteResponses,
    DeleteTournamentApiTournamentsTournamentIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}',
    ...options,
  });

/**
 * Get Tournament
 */
export const getTournamentApiTournamentsTournamentIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTournamentApiTournamentsTournamentIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTournamentApiTournamentsTournamentIdGetResponses,
    GetTournamentApiTournamentsTournamentIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/tournaments/{tournament_id}',
    ...options,
  });

/**
 * Update Tournament By Id
 */
export const updateTournamentByIdApiTournamentsTournamentIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTournamentByIdApiTournamentsTournamentIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateTournamentByIdApiTournamentsTournamentIdPutResponses,
    UpdateTournamentByIdApiTournamentsTournamentIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Available Inputs
 */
export const getAvailableInputsApiTournamentsTournamentIdAvailableInputsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponses,
    GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/available_inputs',
    ...options,
  });

/**
 * Change Status
 *
 * Make a tournament archived or non-archived.
 */
export const changeStatusApiTournamentsTournamentIdChangeStatusPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChangeStatusApiTournamentsTournamentIdChangeStatusPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponses,
    ChangeStatusApiTournamentsTournamentIdChangeStatusPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/change-status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Courts
 */
export const getCourtsApiTournamentsTournamentIdCourtsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCourtsApiTournamentsTournamentIdCourtsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCourtsApiTournamentsTournamentIdCourtsGetResponses,
    GetCourtsApiTournamentsTournamentIdCourtsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/tournaments/{tournament_id}/courts',
    ...options,
  });

/**
 * Create Court
 */
export const createCourtApiTournamentsTournamentIdCourtsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCourtApiTournamentsTournamentIdCourtsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCourtApiTournamentsTournamentIdCourtsPostResponses,
    CreateCourtApiTournamentsTournamentIdCourtsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/courts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Court
 */
export const deleteCourtApiTournamentsTournamentIdCourtsCourtIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteResponses,
    DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/courts/{court_id}',
    ...options,
  });

/**
 * Update Court By Id
 */
export const updateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutResponses,
    UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/courts/{court_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Upload Logo
 */
export const uploadLogoApiTournamentsTournamentIdLogoPost = <ThrowOnError extends boolean = false>(
  options: Options<UploadLogoApiTournamentsTournamentIdLogoPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadLogoApiTournamentsTournamentIdLogoPostResponses,
    UploadLogoApiTournamentsTournamentIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Create Match
 */
export const createMatchApiTournamentsTournamentIdMatchesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMatchApiTournamentsTournamentIdMatchesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateMatchApiTournamentsTournamentIdMatchesPostResponses,
    CreateMatchApiTournamentsTournamentIdMatchesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/matches',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Match
 */
export const deleteMatchApiTournamentsTournamentIdMatchesMatchIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponses,
    DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/matches/{match_id}',
    ...options,
  });

/**
 * Update Match By Id
 */
export const updateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponses,
    UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/matches/{match_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Reschedule Match
 */
export const rescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
    RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/matches/{match_id}/reschedule',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Next Stage Rankings
 *
 * Get the rankings for the stage items in this stage.
 */
export const getNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponses,
    GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/next_stage_rankings',
    ...options,
  });

/**
 * Get Players
 */
export const getPlayersApiTournamentsTournamentIdPlayersGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetPlayersApiTournamentsTournamentIdPlayersGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPlayersApiTournamentsTournamentIdPlayersGetResponses,
    GetPlayersApiTournamentsTournamentIdPlayersGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/players',
    ...options,
  });

/**
 * Create Single Player
 */
export const createSinglePlayerApiTournamentsTournamentIdPlayersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSinglePlayerApiTournamentsTournamentIdPlayersPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponses,
    CreateSinglePlayerApiTournamentsTournamentIdPlayersPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/players',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Player
 */
export const deletePlayerApiTournamentsTournamentIdPlayersPlayerIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
    DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/players/{player_id}',
    ...options,
  });

/**
 * Update Player By Id
 */
export const updatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponses,
    UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/players/{player_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Multiple Players
 */
export const createMultiplePlayersApiTournamentsTournamentIdPlayersMultiPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponses,
    CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/players_multi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Rankings
 */
export const getRankingsApiTournamentsTournamentIdRankingsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetRankingsApiTournamentsTournamentIdRankingsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetRankingsApiTournamentsTournamentIdRankingsGetResponses,
    GetRankingsApiTournamentsTournamentIdRankingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/tournaments/{tournament_id}/rankings',
    ...options,
  });

/**
 * Create Ranking
 */
export const createRankingApiTournamentsTournamentIdRankingsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRankingApiTournamentsTournamentIdRankingsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateRankingApiTournamentsTournamentIdRankingsPostResponses,
    CreateRankingApiTournamentsTournamentIdRankingsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/rankings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Ranking
 */
export const deleteRankingApiTournamentsTournamentIdRankingsRankingIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponses,
    DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/rankings/{ranking_id}',
    ...options,
  });

/**
 * Update Ranking By Id
 */
export const updateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponses,
    UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/rankings/{ranking_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Round
 */
export const createRoundApiTournamentsTournamentIdRoundsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRoundApiTournamentsTournamentIdRoundsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateRoundApiTournamentsTournamentIdRoundsPostResponses,
    CreateRoundApiTournamentsTournamentIdRoundsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/rounds',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Round
 */
export const deleteRoundApiTournamentsTournamentIdRoundsRoundIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponses,
    DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/rounds/{round_id}',
    ...options,
  });

/**
 * Update Round By Id
 */
export const updateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponses,
    UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/rounds/{round_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Schedule Matches
 */
export const scheduleMatchesApiTournamentsTournamentIdScheduleMatchesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponses,
    ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/schedule_matches',
    ...options,
  });

/**
 * Create Stage Item
 */
export const createStageItemApiTournamentsTournamentIdStageItemsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateStageItemApiTournamentsTournamentIdStageItemsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateStageItemApiTournamentsTournamentIdStageItemsPostResponses,
    CreateStageItemApiTournamentsTournamentIdStageItemsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stage_items',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Stage Item
 */
export const deleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
    DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}',
    ...options,
  });

/**
 * Update Stage Item
 */
export const updateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponses,
    UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Stage Item Input
 */
export const updateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).put<
      UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
      UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}/inputs/{stage_item_input_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

/**
 * Reassign Rounds
 */
export const reassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostResponses,
    ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}/reassign_rounds',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Start Next Round
 */
export const startNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses,
    StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}/start_next_round',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Matches To Schedule
 */
export const getMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).get<
      GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses,
      GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}/upcoming_matches',
      ...options,
    });

/**
 * Get Stages
 */
export const getStagesApiTournamentsTournamentIdStagesGet = <ThrowOnError extends boolean = false>(
  options: Options<GetStagesApiTournamentsTournamentIdStagesGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetStagesApiTournamentsTournamentIdStagesGetResponses,
    GetStagesApiTournamentsTournamentIdStagesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/tournaments/{tournament_id}/stages',
    ...options,
  });

/**
 * Create Stage
 */
export const createStageApiTournamentsTournamentIdStagesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateStageApiTournamentsTournamentIdStagesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateStageApiTournamentsTournamentIdStagesPostResponses,
    CreateStageApiTournamentsTournamentIdStagesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stages',
    ...options,
  });

/**
 * Activate Next Stage
 */
export const activateNextStageApiTournamentsTournamentIdStagesActivatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ActivateNextStageApiTournamentsTournamentIdStagesActivatePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponses,
    ActivateNextStageApiTournamentsTournamentIdStagesActivatePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stages/activate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Stage
 */
export const deleteStageApiTournamentsTournamentIdStagesStageIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponses,
    DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stages/{stage_id}',
    ...options,
  });

/**
 * Update Stage
 */
export const updateStageApiTournamentsTournamentIdStagesStageIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStageApiTournamentsTournamentIdStagesStageIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponses,
    UpdateStageApiTournamentsTournamentIdStagesStageIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/stages/{stage_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Teams
 */
export const getTeamsApiTournamentsTournamentIdTeamsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTeamsApiTournamentsTournamentIdTeamsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTeamsApiTournamentsTournamentIdTeamsGetResponses,
    GetTeamsApiTournamentsTournamentIdTeamsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/tournaments/{tournament_id}/teams',
    ...options,
  });

/**
 * Create Team
 */
export const createTeamApiTournamentsTournamentIdTeamsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTeamApiTournamentsTournamentIdTeamsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateTeamApiTournamentsTournamentIdTeamsPostResponses,
    CreateTeamApiTournamentsTournamentIdTeamsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/teams',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Team
 */
export const deleteTeamApiTournamentsTournamentIdTeamsTeamIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponses,
    DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/teams/{team_id}',
    ...options,
  });

/**
 * Update Team By Id
 */
export const updateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponses,
    UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/teams/{team_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Team Logo
 */
export const updateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
    UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/teams/{team_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Create Multiple Teams
 */
export const createMultipleTeamsApiTournamentsTournamentIdTeamsMultiPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponses,
    CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tournaments/{tournament_id}/teams_multi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get User
 */
export const getUserApiUsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserApiUsersMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetUserApiUsersMeGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/me',
    ...options,
  });

/**
 * Register User
 */
export const registerUserApiUsersRegisterPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserApiUsersRegisterPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RegisterUserApiUsersRegisterPostResponses,
    RegisterUserApiUsersRegisterPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/users/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Register Demo User
 */
export const registerDemoUserApiUsersRegisterDemoPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterDemoUserApiUsersRegisterDemoPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RegisterDemoUserApiUsersRegisterDemoPostResponses,
    RegisterDemoUserApiUsersRegisterDemoPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/users/register_demo',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Me
 */
export const getMeApiUsersUserIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetMeApiUsersUserIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetMeApiUsersUserIdGetResponses,
    GetMeApiUsersUserIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{user_id}',
    ...options,
  });

/**
 * Update User Details
 */
export const updateUserDetailsApiUsersUserIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserDetailsApiUsersUserIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUserDetailsApiUsersUserIdPutResponses,
    UpdateUserDetailsApiUsersUserIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Put User Password
 */
export const putUserPasswordApiUsersUserIdPasswordPut = <ThrowOnError extends boolean = false>(
  options: Options<PutUserPasswordApiUsersUserIdPasswordPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutUserPasswordApiUsersUserIdPasswordPutResponses,
    PutUserPasswordApiUsersUserIdPasswordPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{user_id}/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Frontend
 */
export const frontendFullPathGet = <ThrowOnError extends boolean = false>(
  options: Options<FrontendFullPathGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    FrontendFullPathGetResponses,
    FrontendFullPathGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/{full_path}',
    ...options,
  });
