// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login_for_access_token_api_token_post
 */
export type BodyLoginForAccessTokenApiTokenPost = {
  /**
   * Client Id
   */
  client_id: string | null;
  /**
   * Client Secret
   */
  client_secret: string | null;
  /**
   * Grant Type
   */
  grant_type: string | null;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope: string;
  /**
   * Username
   */
  username: string;
};

/**
 * Body_update_team_logo_api_tournaments__tournament_id__teams__team_id__logo_post
 */
export type BodyUpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPost = {
  /**
   * File
   */
  file: Blob | File | null;
};

/**
 * Body_upload_logo_api_tournaments__tournament_id__logo_post
 */
export type BodyUploadLogoApiTournamentsTournamentIdLogoPost = {
  /**
   * File
   */
  file: Blob | File | null;
};

/**
 * Club
 */
export type Club = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
};

/**
 * ClubCreateBody
 */
export type ClubCreateBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * ClubResponse
 */
export type ClubResponse = {
  data: Club | null;
};

/**
 * ClubUpdateBody
 */
export type ClubUpdateBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * ClubsResponse
 */
export type ClubsResponse = {
  /**
   * Data
   */
  data: Array<Club>;
};

/**
 * Court
 */
export type Court = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
};

/**
 * CourtBody
 */
export type CourtBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * CourtsResponse
 */
export type CourtsResponse = {
  /**
   * Data
   */
  data: Array<Court>;
};

/**
 * DemoUserToRegister
 */
export type DemoUserToRegister = {
  /**
   * Captcha Token
   */
  captcha_token: string;
};

/**
 * FullTeamWithPlayers
 */
export type FullTeamWithPlayers = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Created
   */
  created: string;
  /**
   * Draws
   */
  draws: number;
  /**
   * Elo Score
   */
  elo_score: string;
  /**
   * Id
   */
  id: number;
  /**
   * Logo Path
   */
  logo_path: string | null;
  /**
   * Losses
   */
  losses: number;
  /**
   * Name
   */
  name: string;
  /**
   * Players
   */
  players: Array<Player>;
  /**
   * Swiss Score
   */
  swiss_score: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Wins
   */
  wins: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Match
 */
export type Match = {
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Created
   */
  created: string;
  /**
   * Custom Duration Minutes
   */
  custom_duration_minutes: number | null;
  /**
   * Custom Margin Minutes
   */
  custom_margin_minutes: number | null;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Id
   */
  id: number;
  /**
   * Is Played
   */
  is_played: boolean;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Position In Schedule
   */
  position_in_schedule: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1
   */
  stage_item_input1: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty | null;
  /**
   * Stage Item Input1 Conflict
   */
  stage_item_input1_conflict: boolean;
  /**
   * Stage Item Input1 Id
   */
  stage_item_input1_id: number | null;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input1 Score Half Time
   */
  stage_item_input1_score_half_time: number | null;
  /**
   * Stage Item Input1 Winner From Match Id
   */
  stage_item_input1_winner_from_match_id: number | null;
  /**
   * Stage Item Input2
   */
  stage_item_input2: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty | null;
  /**
   * Stage Item Input2 Conflict
   */
  stage_item_input2_conflict: boolean;
  /**
   * Stage Item Input2 Id
   */
  stage_item_input2_id: number | null;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Stage Item Input2 Score Half Time
   */
  stage_item_input2_score_half_time: number | null;
  /**
   * Stage Item Input2 Winner From Match Id
   */
  stage_item_input2_winner_from_match_id: number | null;
  /**
   * Start Time
   */
  start_time: string | null;
};

/**
 * MatchBody
 */
export type MatchBody = {
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Custom Duration Minutes
   */
  custom_duration_minutes: number | null;
  /**
   * Custom Margin Minutes
   */
  custom_margin_minutes: number | null;
  /**
   * Is Played
   */
  is_played: boolean;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input1 Score Half Time
   */
  stage_item_input1_score_half_time: number | null;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Stage Item Input2 Score Half Time
   */
  stage_item_input2_score_half_time: number | null;
};

/**
 * MatchCreateBodyFrontend
 */
export type MatchCreateBodyFrontend = {
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1 Id
   */
  stage_item_input1_id: number | null;
  /**
   * Stage Item Input1 Winner From Match Id
   */
  stage_item_input1_winner_from_match_id: number | null;
  /**
   * Stage Item Input2 Id
   */
  stage_item_input2_id: number | null;
  /**
   * Stage Item Input2 Winner From Match Id
   */
  stage_item_input2_winner_from_match_id: number | null;
};

/**
 * MatchRescheduleBody
 */
export type MatchRescheduleBody = {
  /**
   * New Court Id
   */
  new_court_id: number;
  /**
   * New Position
   */
  new_position: number;
  /**
   * Old Court Id
   */
  old_court_id: number;
  /**
   * Old Position
   */
  old_position: number;
};

/**
 * MatchRoundAssignment
 */
export type MatchRoundAssignment = {
  /**
   * Match Id
   */
  match_id: number;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Swap Teams
   */
  swap_teams: boolean;
};

/**
 * MatchRoundAssignmentsBody
 */
export type MatchRoundAssignmentsBody = {
  /**
   * Assignments
   */
  assignments: Array<MatchRoundAssignment>;
};

/**
 * MatchWithDetails
 *
 * MatchWithDetails has zero or one defined stage item inputs, but not both.
 */
export type MatchWithDetails = {
  court: Court | null;
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Created
   */
  created: string;
  /**
   * Custom Duration Minutes
   */
  custom_duration_minutes: number | null;
  /**
   * Custom Margin Minutes
   */
  custom_margin_minutes: number | null;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Id
   */
  id: number;
  /**
   * Is Played
   */
  is_played: boolean;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Position In Schedule
   */
  position_in_schedule: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1
   */
  stage_item_input1: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty | null;
  /**
   * Stage Item Input1 Conflict
   */
  stage_item_input1_conflict: boolean;
  /**
   * Stage Item Input1 Id
   */
  stage_item_input1_id: number | null;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input1 Score Half Time
   */
  stage_item_input1_score_half_time: number | null;
  /**
   * Stage Item Input1 Winner From Match Id
   */
  stage_item_input1_winner_from_match_id: number | null;
  /**
   * Stage Item Input2
   */
  stage_item_input2: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty | null;
  /**
   * Stage Item Input2 Conflict
   */
  stage_item_input2_conflict: boolean;
  /**
   * Stage Item Input2 Id
   */
  stage_item_input2_id: number | null;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Stage Item Input2 Score Half Time
   */
  stage_item_input2_score_half_time: number | null;
  /**
   * Stage Item Input2 Winner From Match Id
   */
  stage_item_input2_winner_from_match_id: number | null;
  /**
   * Start Time
   */
  start_time: string | null;
};

/**
 * MatchWithDetailsDefinitive
 */
export type MatchWithDetailsDefinitive = {
  court: Court | null;
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Created
   */
  created: string;
  /**
   * Custom Duration Minutes
   */
  custom_duration_minutes: number | null;
  /**
   * Custom Margin Minutes
   */
  custom_margin_minutes: number | null;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Id
   */
  id: number;
  /**
   * Is Played
   */
  is_played: boolean;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Position In Schedule
   */
  position_in_schedule: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1
   */
  stage_item_input1: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty;
  /**
   * Stage Item Input1 Conflict
   */
  stage_item_input1_conflict: boolean;
  /**
   * Stage Item Input1 Id
   */
  stage_item_input1_id: number | null;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input1 Score Half Time
   */
  stage_item_input1_score_half_time: number | null;
  /**
   * Stage Item Input1 Winner From Match Id
   */
  stage_item_input1_winner_from_match_id: number | null;
  /**
   * Stage Item Input2
   */
  stage_item_input2: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty;
  /**
   * Stage Item Input2 Conflict
   */
  stage_item_input2_conflict: boolean;
  /**
   * Stage Item Input2 Id
   */
  stage_item_input2_id: number | null;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Stage Item Input2 Score Half Time
   */
  stage_item_input2_score_half_time: number | null;
  /**
   * Stage Item Input2 Winner From Match Id
   */
  stage_item_input2_winner_from_match_id: number | null;
  /**
   * Start Time
   */
  start_time: string | null;
};

/**
 * PaginatedPlayers
 */
export type PaginatedPlayers = {
  /**
   * Count
   */
  count: number;
  /**
   * Players
   */
  players: Array<Player>;
};

/**
 * PaginatedTeams
 */
export type PaginatedTeams = {
  /**
   * Count
   */
  count: number;
  /**
   * Teams
   */
  teams: Array<FullTeamWithPlayers>;
};

/**
 * Player
 */
export type Player = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Created
   */
  created: string;
  /**
   * Draws
   */
  draws: number;
  /**
   * Elo Score
   */
  elo_score: string;
  /**
   * Id
   */
  id: number;
  /**
   * Losses
   */
  losses: number;
  /**
   * Name
   */
  name: string;
  /**
   * Swiss Score
   */
  swiss_score: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Wins
   */
  wins: number;
};

/**
 * PlayerBody
 */
export type PlayerBody = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Name
   */
  name: string;
};

/**
 * PlayerMultiBody
 */
export type PlayerMultiBody = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Names
   */
  names: string;
};

/**
 * PlayersResponse
 */
export type PlayersResponse = {
  data: PaginatedPlayers;
};

/**
 * Ranking
 */
export type Ranking = {
  /**
   * Add Score Points
   */
  add_score_points: boolean;
  /**
   * Created
   */
  created: string;
  /**
   * Draw Points
   */
  draw_points: string;
  /**
   * Id
   */
  id: number;
  /**
   * Loss Points
   */
  loss_points: string;
  /**
   * Name
   */
  name: string;
  /**
   * Position
   */
  position: number;
  /**
   * Standings Zones
   */
  standings_zones: Array<RankingZone>;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Win Points
   */
  win_points: string;
};

/**
 * RankingBody
 */
export type RankingBody = {
  /**
   * Add Score Points
   */
  add_score_points: boolean;
  /**
   * Draw Points
   */
  draw_points: number | string;
  /**
   * Loss Points
   */
  loss_points: number | string;
  /**
   * Name
   */
  name: string;
  /**
   * Position
   */
  position: number;
  /**
   * Standings Zones
   */
  standings_zones: Array<RankingZone>;
  /**
   * Win Points
   */
  win_points: number | string;
};

/**
 * RankingCreateBody
 */
export type RankingCreateBody = {
  /**
   * Add Score Points
   */
  add_score_points: boolean;
  /**
   * Draw Points
   */
  draw_points: number | string;
  /**
   * Loss Points
   */
  loss_points: number | string;
  /**
   * Name
   */
  name: string;
  /**
   * Standings Zones
   */
  standings_zones: Array<RankingZone>;
  /**
   * Win Points
   */
  win_points: number | string;
};

/**
 * RankingZone
 */
export type RankingZone = {
  /**
   * Color
   */
  color: string;
  /**
   * Count
   */
  count: number;
  /**
   * Direction
   */
  direction: 'top' | 'bottom';
  /**
   * Label
   */
  label: string;
};

/**
 * RankingsResponse
 */
export type RankingsResponse = {
  /**
   * Data
   */
  data: Array<Ranking>;
};

/**
 * RoundCreateBody
 */
export type RoundCreateBody = {
  /**
   * Name
   */
  name: string | null;
  /**
   * Stage Item Id
   */
  stage_item_id: number;
};

/**
 * RoundUpdateBody
 */
export type RoundUpdateBody = {
  /**
   * Is Draft
   */
  is_draft: boolean;
  /**
   * Name
   */
  name: string;
};

/**
 * RoundWithMatches
 */
export type RoundWithMatches = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Is Draft
   */
  is_draft: boolean;
  /**
   * Matches
   */
  matches: Array<MatchWithDetailsDefinitive | MatchWithDetails>;
  /**
   * Name
   */
  name: string;
  /**
   * Stage Item Id
   */
  stage_item_id: number;
};

/**
 * SingleCourtResponse
 */
export type SingleCourtResponse = {
  data: Court;
};

/**
 * SingleMatchResponse
 */
export type SingleMatchResponse = {
  data: Match;
};

/**
 * SinglePlayerResponse
 */
export type SinglePlayerResponse = {
  data: Player;
};

/**
 * SingleTeamResponse
 */
export type SingleTeamResponse = {
  data: Team;
};

/**
 * StageActivateBody
 */
export type StageActivateBody = {
  /**
   * Direction
   */
  direction: 'next' | 'previous';
};

/**
 * StageItemActivateNextBody
 */
export type StageItemActivateNextBody = {
  /**
   * Adjust To Time
   */
  adjust_to_time: string | null;
};

/**
 * StageItemCreateBody
 */
export type StageItemCreateBody = {
  /**
   * Name
   */
  name: string | null;
  /**
   * Ranking Id
   */
  ranking_id: number | null;
  /**
   * Stage Id
   */
  stage_id: number;
  /**
   * Team Count
   */
  team_count: number;
  type: StageType;
};

/**
 * StageItemInputEmpty
 */
export type StageItemInputEmpty = {
  /**
   * Draws
   */
  draws: number;
  /**
   * Goals Against
   */
  goals_against: number;
  /**
   * Goals For
   */
  goals_for: number;
  /**
   * Id
   */
  id: number;
  /**
   * Losses
   */
  losses: number;
  /**
   * Points
   */
  points: string;
  /**
   * Slot
   */
  slot: number;
  /**
   * Stage Item Id
   */
  stage_item_id: number | null;
  /**
   * Team Id
   */
  team_id: null;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: null;
  /**
   * Winner Position
   */
  winner_position: null;
  /**
   * Wins
   */
  wins: number;
};

/**
 * StageItemInputFinal
 */
export type StageItemInputFinal = {
  /**
   * Draws
   */
  draws: number;
  /**
   * Goals Against
   */
  goals_against: number;
  /**
   * Goals For
   */
  goals_for: number;
  /**
   * Id
   */
  id: number;
  /**
   * Losses
   */
  losses: number;
  /**
   * Points
   */
  points: string;
  /**
   * Slot
   */
  slot: number;
  /**
   * Stage Item Id
   */
  stage_item_id: number | null;
  team: Team;
  /**
   * Team Id
   */
  team_id: number;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: number | null;
  /**
   * Winner Position
   */
  winner_position: number | null;
  /**
   * Wins
   */
  wins: number;
};

/**
 * StageItemInputOptionFinal
 */
export type StageItemInputOptionFinal = {
  /**
   * Already Taken
   */
  already_taken: boolean;
  /**
   * Team Id
   */
  team_id: number;
};

/**
 * StageItemInputOptionTentative
 */
export type StageItemInputOptionTentative = {
  /**
   * Already Taken
   */
  already_taken: boolean;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: number;
  /**
   * Winner Position
   */
  winner_position: number;
};

/**
 * StageItemInputOptionsResponse
 */
export type StageItemInputOptionsResponse = {
  /**
   * Data
   */
  data: {
    [key: string]: Array<StageItemInputOptionTentative | StageItemInputOptionFinal>;
  };
};

/**
 * StageItemInputTentative
 */
export type StageItemInputTentative = {
  /**
   * Draws
   */
  draws: number;
  /**
   * Goals Against
   */
  goals_against: number;
  /**
   * Goals For
   */
  goals_for: number;
  /**
   * Id
   */
  id: number;
  /**
   * Losses
   */
  losses: number;
  /**
   * Points
   */
  points: string;
  /**
   * Slot
   */
  slot: number;
  /**
   * Stage Item Id
   */
  stage_item_id: number | null;
  /**
   * Team Id
   */
  team_id: null;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: number;
  /**
   * Winner Position
   */
  winner_position: number;
  /**
   * Wins
   */
  wins: number;
};

/**
 * StageItemInputUpdate
 */
export type StageItemInputUpdate = {
  stage_item_input: StageItemInputTentative;
  team: Team;
};

/**
 * StageItemInputUpdateBodyEmpty
 */
export type StageItemInputUpdateBodyEmpty = {
  /**
   * Team Id
   */
  team_id: null;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: null;
  /**
   * Winner Position
   */
  winner_position: null;
};

/**
 * StageItemInputUpdateBodyFinal
 */
export type StageItemInputUpdateBodyFinal = {
  /**
   * Team Id
   */
  team_id: number;
};

/**
 * StageItemInputUpdateBodyTentative
 */
export type StageItemInputUpdateBodyTentative = {
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: number;
  /**
   * Winner Position
   */
  winner_position: number;
};

/**
 * StageItemUpdateBody
 */
export type StageItemUpdateBody = {
  /**
   * Name
   */
  name: string;
  /**
   * Ranking Id
   */
  ranking_id: number;
};

/**
 * StageItemWithRounds
 */
export type StageItemWithRounds = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Inputs
   */
  inputs: Array<StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty>;
  /**
   * Name
   */
  name: string;
  /**
   * Ranking Id
   */
  ranking_id: number | null;
  /**
   * Rounds
   */
  rounds: Array<RoundWithMatches>;
  /**
   * Stage Id
   */
  stage_id: number;
  /**
   * Team Count
   */
  team_count: number;
  type: StageType;
  /**
   * Type Name
   */
  type_name: string;
};

/**
 * StageRankingResponse
 */
export type StageRankingResponse = {
  /**
   * Data
   */
  data: {
    [key: string]: Array<StageItemInputUpdate>;
  };
};

/**
 * StageType
 */
export type StageType = 'ROUND_ROBIN' | 'SINGLE_ELIMINATION' | 'SWISS';

/**
 * StageUpdateBody
 */
export type StageUpdateBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * StageWithStageItems
 */
export type StageWithStageItems = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Name
   */
  name: string;
  /**
   * Stage Items
   */
  stage_items: Array<StageItemWithRounds>;
  /**
   * Tournament Id
   */
  tournament_id: number;
};

/**
 * StagesWithStageItemsResponse
 */
export type StagesWithStageItemsResponse = {
  /**
   * Data
   */
  data: Array<StageWithStageItems>;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
  /**
   * Success
   */
  success: boolean;
};

/**
 * SuggestedMatch
 */
export type SuggestedMatch = {
  /**
   * Elo Diff
   */
  elo_diff: string;
  /**
   * Is Recommended
   */
  is_recommended: boolean;
  /**
   * Player Behind Schedule Count
   */
  player_behind_schedule_count: number;
  /**
   * Stage Item Input1
   */
  stage_item_input1: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty;
  /**
   * Stage Item Input2
   */
  stage_item_input2: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty;
  /**
   * Swiss Diff
   */
  swiss_diff: string;
  /**
   * Times Played Sum
   */
  times_played_sum: number;
};

/**
 * Team
 */
export type Team = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Created
   */
  created: string;
  /**
   * Draws
   */
  draws: number;
  /**
   * Elo Score
   */
  elo_score: string;
  /**
   * Id
   */
  id: number;
  /**
   * Logo Path
   */
  logo_path: string | null;
  /**
   * Losses
   */
  losses: number;
  /**
   * Name
   */
  name: string;
  /**
   * Swiss Score
   */
  swiss_score: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Wins
   */
  wins: number;
};

/**
 * TeamBody
 */
export type TeamBody = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Name
   */
  name: string;
  /**
   * Player Ids
   */
  player_ids: Array<number>;
};

/**
 * TeamMultiBody
 */
export type TeamMultiBody = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Names
   */
  names: string;
};

/**
 * TeamsWithPlayersResponse
 */
export type TeamsWithPlayersResponse = {
  data: PaginatedTeams;
};

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
  /**
   * User Id
   */
  user_id: number;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
  data: Token;
};

/**
 * Tournament
 */
export type Tournament = {
  /**
   * Auto Assign Courts
   */
  auto_assign_courts: boolean;
  /**
   * Club Id
   */
  club_id: number;
  /**
   * Created
   */
  created: string;
  /**
   * Dashboard Endpoint
   */
  dashboard_endpoint: string | null;
  /**
   * Dashboard Public
   */
  dashboard_public: boolean;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Id
   */
  id: number;
  /**
   * Logo Path
   */
  logo_path: string | null;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Name
   */
  name: string;
  /**
   * Players Can Be In Multiple Teams
   */
  players_can_be_in_multiple_teams: boolean;
  /**
   * Start Time
   */
  start_time: string;
  status: TournamentStatus;
};

/**
 * TournamentBody
 */
export type TournamentBody = {
  /**
   * Auto Assign Courts
   */
  auto_assign_courts: boolean;
  /**
   * Club Id
   */
  club_id: number;
  /**
   * Dashboard Endpoint
   */
  dashboard_endpoint: unknown | string;
  /**
   * Dashboard Public
   */
  dashboard_public: boolean;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Name
   */
  name: string;
  /**
   * Players Can Be In Multiple Teams
   */
  players_can_be_in_multiple_teams: boolean;
  /**
   * Start Time
   */
  start_time: string;
};

/**
 * TournamentChangeStatusBody
 */
export type TournamentChangeStatusBody = {
  status: TournamentStatus;
};

/**
 * TournamentResponse
 */
export type TournamentResponse = {
  data: Tournament;
};

/**
 * TournamentStatus
 */
export type TournamentStatus = 'OPEN' | 'ARCHIVED';

/**
 * TournamentUpdateBody
 */
export type TournamentUpdateBody = {
  /**
   * Auto Assign Courts
   */
  auto_assign_courts: boolean;
  /**
   * Dashboard Endpoint
   */
  dashboard_endpoint: unknown | string;
  /**
   * Dashboard Public
   */
  dashboard_public: boolean;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Name
   */
  name: string;
  /**
   * Players Can Be In Multiple Teams
   */
  players_can_be_in_multiple_teams: boolean;
  /**
   * Start Time
   */
  start_time: string;
};

/**
 * TournamentsResponse
 */
export type TournamentsResponse = {
  /**
   * Data
   */
  data: Array<Tournament>;
};

/**
 * UpcomingMatchesResponse
 */
export type UpcomingMatchesResponse = {
  /**
   * Data
   */
  data: Array<SuggestedMatch>;
};

/**
 * UserAccountType
 */
export type UserAccountType = 'REGULAR' | 'DEMO';

/**
 * UserPasswordToUpdate
 */
export type UserPasswordToUpdate = {
  /**
   * Password
   */
  password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
  account_type: UserAccountType;
  /**
   * Created
   */
  created: string;
  /**
   * Email
   */
  email: string;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
};

/**
 * UserPublicResponse
 */
export type UserPublicResponse = {
  data: UserPublic;
};

/**
 * UserToRegister
 */
export type UserToRegister = {
  /**
   * Captcha Token
   */
  captcha_token: string;
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserToUpdate
 */
export type UserToUpdate = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type GetClubsApiClubsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/clubs';
};

export type GetClubsApiClubsGetResponses = {
  /**
   * Successful Response
   */
  200: ClubsResponse;
};

export type GetClubsApiClubsGetResponse =
  GetClubsApiClubsGetResponses[keyof GetClubsApiClubsGetResponses];

export type CreateNewClubApiClubsPostData = {
  body: ClubCreateBody;
  path?: never;
  query?: never;
  url: '/api/clubs';
};

export type CreateNewClubApiClubsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateNewClubApiClubsPostError =
  CreateNewClubApiClubsPostErrors[keyof CreateNewClubApiClubsPostErrors];

export type CreateNewClubApiClubsPostResponses = {
  /**
   * Successful Response
   */
  200: ClubResponse;
};

export type CreateNewClubApiClubsPostResponse =
  CreateNewClubApiClubsPostResponses[keyof CreateNewClubApiClubsPostResponses];

export type DeleteClubApiClubsClubIdDeleteData = {
  body?: never;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/api/clubs/{club_id}';
};

export type DeleteClubApiClubsClubIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteClubApiClubsClubIdDeleteError =
  DeleteClubApiClubsClubIdDeleteErrors[keyof DeleteClubApiClubsClubIdDeleteErrors];

export type DeleteClubApiClubsClubIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteClubApiClubsClubIdDeleteResponse =
  DeleteClubApiClubsClubIdDeleteResponses[keyof DeleteClubApiClubsClubIdDeleteResponses];

export type UpdateClubApiClubsClubIdPutData = {
  body: ClubUpdateBody;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/api/clubs/{club_id}';
};

export type UpdateClubApiClubsClubIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateClubApiClubsClubIdPutError =
  UpdateClubApiClubsClubIdPutErrors[keyof UpdateClubApiClubsClubIdPutErrors];

export type UpdateClubApiClubsClubIdPutResponses = {
  /**
   * Successful Response
   */
  200: ClubResponse;
};

export type UpdateClubApiClubsClubIdPutResponse =
  UpdateClubApiClubsClubIdPutResponses[keyof UpdateClubApiClubsClubIdPutResponses];

export type GetMetricsApiMetricsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/metrics';
};

export type GetMetricsApiMetricsGetResponses = {
  /**
   * Successful Response
   */
  200: string;
};

export type GetMetricsApiMetricsGetResponse =
  GetMetricsApiMetricsGetResponses[keyof GetMetricsApiMetricsGetResponses];

export type PingApiPingGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/ping';
};

export type PingApiPingGetResponses = {
  /**
   * Response Ping Api Ping Get
   *
   * Successful Response
   */
  200: string;
};

export type PingApiPingGetResponse = PingApiPingGetResponses[keyof PingApiPingGetResponses];

export type LoginForAccessTokenApiTokenPostData = {
  body: BodyLoginForAccessTokenApiTokenPost;
  path?: never;
  query?: never;
  url: '/api/token';
};

export type LoginForAccessTokenApiTokenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginForAccessTokenApiTokenPostError =
  LoginForAccessTokenApiTokenPostErrors[keyof LoginForAccessTokenApiTokenPostErrors];

export type LoginForAccessTokenApiTokenPostResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginForAccessTokenApiTokenPostResponse =
  LoginForAccessTokenApiTokenPostResponses[keyof LoginForAccessTokenApiTokenPostResponses];

export type GetTournamentsApiTournamentsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter
     */
    filter_?: 'ALL' | 'OPEN' | 'ARCHIVED';
    /**
     * Endpoint Name
     */
    endpoint_name?: string | null;
  };
  url: '/api/tournaments';
};

export type GetTournamentsApiTournamentsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTournamentsApiTournamentsGetError =
  GetTournamentsApiTournamentsGetErrors[keyof GetTournamentsApiTournamentsGetErrors];

export type GetTournamentsApiTournamentsGetResponses = {
  /**
   * Successful Response
   */
  200: TournamentsResponse;
};

export type GetTournamentsApiTournamentsGetResponse =
  GetTournamentsApiTournamentsGetResponses[keyof GetTournamentsApiTournamentsGetResponses];

export type CreateTournamentApiTournamentsPostData = {
  body: TournamentBody;
  path?: never;
  query?: never;
  url: '/api/tournaments';
};

export type CreateTournamentApiTournamentsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTournamentApiTournamentsPostError =
  CreateTournamentApiTournamentsPostErrors[keyof CreateTournamentApiTournamentsPostErrors];

export type CreateTournamentApiTournamentsPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateTournamentApiTournamentsPostResponse =
  CreateTournamentApiTournamentsPostResponses[keyof CreateTournamentApiTournamentsPostResponses];

export type DeleteTournamentApiTournamentsTournamentIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}';
};

export type DeleteTournamentApiTournamentsTournamentIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTournamentApiTournamentsTournamentIdDeleteError =
  DeleteTournamentApiTournamentsTournamentIdDeleteErrors[keyof DeleteTournamentApiTournamentsTournamentIdDeleteErrors];

export type DeleteTournamentApiTournamentsTournamentIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteTournamentApiTournamentsTournamentIdDeleteResponse =
  DeleteTournamentApiTournamentsTournamentIdDeleteResponses[keyof DeleteTournamentApiTournamentsTournamentIdDeleteResponses];

export type GetTournamentApiTournamentsTournamentIdGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}';
};

export type GetTournamentApiTournamentsTournamentIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTournamentApiTournamentsTournamentIdGetError =
  GetTournamentApiTournamentsTournamentIdGetErrors[keyof GetTournamentApiTournamentsTournamentIdGetErrors];

export type GetTournamentApiTournamentsTournamentIdGetResponses = {
  /**
   * Successful Response
   */
  200: TournamentResponse;
};

export type GetTournamentApiTournamentsTournamentIdGetResponse =
  GetTournamentApiTournamentsTournamentIdGetResponses[keyof GetTournamentApiTournamentsTournamentIdGetResponses];

export type UpdateTournamentByIdApiTournamentsTournamentIdPutData = {
  body: TournamentUpdateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}';
};

export type UpdateTournamentByIdApiTournamentsTournamentIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTournamentByIdApiTournamentsTournamentIdPutError =
  UpdateTournamentByIdApiTournamentsTournamentIdPutErrors[keyof UpdateTournamentByIdApiTournamentsTournamentIdPutErrors];

export type UpdateTournamentByIdApiTournamentsTournamentIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateTournamentByIdApiTournamentsTournamentIdPutResponse =
  UpdateTournamentByIdApiTournamentsTournamentIdPutResponses[keyof UpdateTournamentByIdApiTournamentsTournamentIdPutResponses];

export type GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/available_inputs';
};

export type GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetError =
  GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetErrors[keyof GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetErrors];

export type GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponses = {
  /**
   * Successful Response
   */
  200: StageItemInputOptionsResponse;
};

export type GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponse =
  GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponses[keyof GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponses];

export type ChangeStatusApiTournamentsTournamentIdChangeStatusPostData = {
  body: TournamentChangeStatusBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/change-status';
};

export type ChangeStatusApiTournamentsTournamentIdChangeStatusPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChangeStatusApiTournamentsTournamentIdChangeStatusPostError =
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostErrors[keyof ChangeStatusApiTournamentsTournamentIdChangeStatusPostErrors];

export type ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponse =
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponses[keyof ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponses];

export type GetCourtsApiTournamentsTournamentIdCourtsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/courts';
};

export type GetCourtsApiTournamentsTournamentIdCourtsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCourtsApiTournamentsTournamentIdCourtsGetError =
  GetCourtsApiTournamentsTournamentIdCourtsGetErrors[keyof GetCourtsApiTournamentsTournamentIdCourtsGetErrors];

export type GetCourtsApiTournamentsTournamentIdCourtsGetResponses = {
  /**
   * Successful Response
   */
  200: CourtsResponse;
};

export type GetCourtsApiTournamentsTournamentIdCourtsGetResponse =
  GetCourtsApiTournamentsTournamentIdCourtsGetResponses[keyof GetCourtsApiTournamentsTournamentIdCourtsGetResponses];

export type CreateCourtApiTournamentsTournamentIdCourtsPostData = {
  body: CourtBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/courts';
};

export type CreateCourtApiTournamentsTournamentIdCourtsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCourtApiTournamentsTournamentIdCourtsPostError =
  CreateCourtApiTournamentsTournamentIdCourtsPostErrors[keyof CreateCourtApiTournamentsTournamentIdCourtsPostErrors];

export type CreateCourtApiTournamentsTournamentIdCourtsPostResponses = {
  /**
   * Successful Response
   */
  200: SingleCourtResponse;
};

export type CreateCourtApiTournamentsTournamentIdCourtsPostResponse =
  CreateCourtApiTournamentsTournamentIdCourtsPostResponses[keyof CreateCourtApiTournamentsTournamentIdCourtsPostResponses];

export type DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Court Id
     */
    court_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/courts/{court_id}';
};

export type DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteError =
  DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteErrors[keyof DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteErrors];

export type DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteResponse =
  DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteResponses[keyof DeleteCourtApiTournamentsTournamentIdCourtsCourtIdDeleteResponses];

export type UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutData = {
  body: CourtBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Court Id
     */
    court_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/courts/{court_id}';
};

export type UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutError =
  UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutErrors[keyof UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutErrors];

export type UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutResponses = {
  /**
   * Successful Response
   */
  200: SingleCourtResponse;
};

export type UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutResponse =
  UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutResponses[keyof UpdateCourtByIdApiTournamentsTournamentIdCourtsCourtIdPutResponses];

export type UploadLogoApiTournamentsTournamentIdLogoPostData = {
  body?: BodyUploadLogoApiTournamentsTournamentIdLogoPost;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/logo';
};

export type UploadLogoApiTournamentsTournamentIdLogoPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadLogoApiTournamentsTournamentIdLogoPostError =
  UploadLogoApiTournamentsTournamentIdLogoPostErrors[keyof UploadLogoApiTournamentsTournamentIdLogoPostErrors];

export type UploadLogoApiTournamentsTournamentIdLogoPostResponses = {
  /**
   * Successful Response
   */
  200: TournamentResponse;
};

export type UploadLogoApiTournamentsTournamentIdLogoPostResponse =
  UploadLogoApiTournamentsTournamentIdLogoPostResponses[keyof UploadLogoApiTournamentsTournamentIdLogoPostResponses];

export type CreateMatchApiTournamentsTournamentIdMatchesPostData = {
  body: MatchCreateBodyFrontend;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/matches';
};

export type CreateMatchApiTournamentsTournamentIdMatchesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMatchApiTournamentsTournamentIdMatchesPostError =
  CreateMatchApiTournamentsTournamentIdMatchesPostErrors[keyof CreateMatchApiTournamentsTournamentIdMatchesPostErrors];

export type CreateMatchApiTournamentsTournamentIdMatchesPostResponses = {
  /**
   * Successful Response
   */
  200: SingleMatchResponse;
};

export type CreateMatchApiTournamentsTournamentIdMatchesPostResponse =
  CreateMatchApiTournamentsTournamentIdMatchesPostResponses[keyof CreateMatchApiTournamentsTournamentIdMatchesPostResponses];

export type DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Match Id
     */
    match_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/matches/{match_id}';
};

export type DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteError =
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteErrors[keyof DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteErrors];

export type DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponse =
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponses[keyof DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponses];

export type UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutData = {
  body: MatchBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Match Id
     */
    match_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/matches/{match_id}';
};

export type UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutError =
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutErrors[keyof UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutErrors];

export type UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponse =
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponses[keyof UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponses];

export type RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostData = {
  body: MatchRescheduleBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Match Id
     */
    match_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/matches/{match_id}/reschedule';
};

export type RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostError =
  RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostErrors[keyof RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostErrors];

export type RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostResponse =
  RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostResponses[keyof RescheduleMatchApiTournamentsTournamentIdMatchesMatchIdReschedulePostResponses];

export type GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/next_stage_rankings';
};

export type GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetError =
  GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetErrors[keyof GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetErrors];

export type GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponses = {
  /**
   * Successful Response
   */
  200: StageRankingResponse;
};

export type GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponse =
  GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponses[keyof GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponses];

export type GetPlayersApiTournamentsTournamentIdPlayersGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: {
    /**
     * Not In Team
     */
    not_in_team?: boolean;
    /**
     * Limit
     *
     * Max number of results in a single page.
     */
    limit?: number;
    /**
     * Offset
     *
     * Filter results starting from this offset.
     */
    offset?: number;
    /**
     * Sort Direction
     */
    sort_direction?: 'asc' | 'desc';
    /**
     * Sort By
     */
    sort_by?:
      | 'name'
      | 'elo_score'
      | 'swiss_score'
      | 'wins'
      | 'draws'
      | 'losses'
      | 'active'
      | 'created';
  };
  url: '/api/tournaments/{tournament_id}/players';
};

export type GetPlayersApiTournamentsTournamentIdPlayersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPlayersApiTournamentsTournamentIdPlayersGetError =
  GetPlayersApiTournamentsTournamentIdPlayersGetErrors[keyof GetPlayersApiTournamentsTournamentIdPlayersGetErrors];

export type GetPlayersApiTournamentsTournamentIdPlayersGetResponses = {
  /**
   * Successful Response
   */
  200: PlayersResponse;
};

export type GetPlayersApiTournamentsTournamentIdPlayersGetResponse =
  GetPlayersApiTournamentsTournamentIdPlayersGetResponses[keyof GetPlayersApiTournamentsTournamentIdPlayersGetResponses];

export type CreateSinglePlayerApiTournamentsTournamentIdPlayersPostData = {
  body: PlayerBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/players';
};

export type CreateSinglePlayerApiTournamentsTournamentIdPlayersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSinglePlayerApiTournamentsTournamentIdPlayersPostError =
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostErrors[keyof CreateSinglePlayerApiTournamentsTournamentIdPlayersPostErrors];

export type CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponse =
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponses[keyof CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponses];

export type DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Player Id
     */
    player_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/players/{player_id}';
};

export type DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteError =
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteErrors[keyof DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteErrors];

export type DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponse =
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponses[keyof DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponses];

export type UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutData = {
  body: PlayerBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Player Id
     */
    player_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/players/{player_id}';
};

export type UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutError =
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutErrors[keyof UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutErrors];

export type UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponses = {
  /**
   * Successful Response
   */
  200: SinglePlayerResponse;
};

export type UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponse =
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponses[keyof UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponses];

export type CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostData = {
  body: PlayerMultiBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/players_multi';
};

export type CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostError =
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostErrors[keyof CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostErrors];

export type CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponse =
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponses[keyof CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponses];

export type GetRankingsApiTournamentsTournamentIdRankingsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/rankings';
};

export type GetRankingsApiTournamentsTournamentIdRankingsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetRankingsApiTournamentsTournamentIdRankingsGetError =
  GetRankingsApiTournamentsTournamentIdRankingsGetErrors[keyof GetRankingsApiTournamentsTournamentIdRankingsGetErrors];

export type GetRankingsApiTournamentsTournamentIdRankingsGetResponses = {
  /**
   * Successful Response
   */
  200: RankingsResponse;
};

export type GetRankingsApiTournamentsTournamentIdRankingsGetResponse =
  GetRankingsApiTournamentsTournamentIdRankingsGetResponses[keyof GetRankingsApiTournamentsTournamentIdRankingsGetResponses];

export type CreateRankingApiTournamentsTournamentIdRankingsPostData = {
  body: RankingCreateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/rankings';
};

export type CreateRankingApiTournamentsTournamentIdRankingsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateRankingApiTournamentsTournamentIdRankingsPostError =
  CreateRankingApiTournamentsTournamentIdRankingsPostErrors[keyof CreateRankingApiTournamentsTournamentIdRankingsPostErrors];

export type CreateRankingApiTournamentsTournamentIdRankingsPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateRankingApiTournamentsTournamentIdRankingsPostResponse =
  CreateRankingApiTournamentsTournamentIdRankingsPostResponses[keyof CreateRankingApiTournamentsTournamentIdRankingsPostResponses];

export type DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Ranking Id
     */
    ranking_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/rankings/{ranking_id}';
};

export type DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteError =
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteErrors[keyof DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteErrors];

export type DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponse =
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponses[keyof DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponses];

export type UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutData = {
  body: RankingBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Ranking Id
     */
    ranking_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/rankings/{ranking_id}';
};

export type UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutError =
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutErrors[keyof UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutErrors];

export type UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponse =
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponses[keyof UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponses];

export type CreateRoundApiTournamentsTournamentIdRoundsPostData = {
  body: RoundCreateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/rounds';
};

export type CreateRoundApiTournamentsTournamentIdRoundsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateRoundApiTournamentsTournamentIdRoundsPostError =
  CreateRoundApiTournamentsTournamentIdRoundsPostErrors[keyof CreateRoundApiTournamentsTournamentIdRoundsPostErrors];

export type CreateRoundApiTournamentsTournamentIdRoundsPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateRoundApiTournamentsTournamentIdRoundsPostResponse =
  CreateRoundApiTournamentsTournamentIdRoundsPostResponses[keyof CreateRoundApiTournamentsTournamentIdRoundsPostResponses];

export type DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Round Id
     */
    round_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/rounds/{round_id}';
};

export type DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteError =
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteErrors[keyof DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteErrors];

export type DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponse =
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponses[keyof DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponses];

export type UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutData = {
  body: RoundUpdateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Round Id
     */
    round_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/rounds/{round_id}';
};

export type UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutError =
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutErrors[keyof UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutErrors];

export type UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponse =
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponses[keyof UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponses];

export type ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/schedule_matches';
};

export type ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostError =
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostErrors[keyof ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostErrors];

export type ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponse =
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponses[keyof ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponses];

export type CreateStageItemApiTournamentsTournamentIdStageItemsPostData = {
  body: StageItemCreateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/stage_items';
};

export type CreateStageItemApiTournamentsTournamentIdStageItemsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateStageItemApiTournamentsTournamentIdStageItemsPostError =
  CreateStageItemApiTournamentsTournamentIdStageItemsPostErrors[keyof CreateStageItemApiTournamentsTournamentIdStageItemsPostErrors];

export type CreateStageItemApiTournamentsTournamentIdStageItemsPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateStageItemApiTournamentsTournamentIdStageItemsPostResponse =
  CreateStageItemApiTournamentsTournamentIdStageItemsPostResponses[keyof CreateStageItemApiTournamentsTournamentIdStageItemsPostResponses];

export type DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Item Id
     */
    stage_item_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}';
};

export type DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteError =
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteErrors[keyof DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteErrors];

export type DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponse =
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponses[keyof DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponses];

export type UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutData = {
  body: StageItemUpdateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Item Id
     */
    stage_item_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}';
};

export type UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutError =
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutErrors[keyof UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutErrors];

export type UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponse =
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponses[keyof UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponses];

export type UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData =
  {
    /**
     * Stage Item Body
     */
    body:
      | StageItemInputUpdateBodyTentative
      | StageItemInputUpdateBodyFinal
      | StageItemInputUpdateBodyEmpty;
    path: {
      /**
       * Tournament Id
       */
      tournament_id: number;
      /**
       * Stage Item Id
       */
      stage_item_id: number;
      /**
       * Stage Item Input Id
       */
      stage_item_input_id: number;
    };
    query?: never;
    url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}/inputs/{stage_item_input_id}';
  };

export type UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutError =
  UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors[keyof UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors];

export type UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses =
  {
    /**
     * Successful Response
     */
    200: SuccessResponse;
  };

export type UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponse =
  UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses[keyof UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses];

export type ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostData = {
  body: MatchRoundAssignmentsBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Item Id
     */
    stage_item_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}/reassign_rounds';
};

export type ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostError =
  ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostErrors[keyof ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostErrors];

export type ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostResponses =
  {
    /**
     * Successful Response
     */
    200: SuccessResponse;
  };

export type ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostResponse =
  ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostResponses[keyof ReassignRoundsApiTournamentsTournamentIdStageItemsStageItemIdReassignRoundsPostResponses];

export type StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostData = {
  body: StageItemActivateNextBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Item Id
     */
    stage_item_id: number;
  };
  query?: {
    /**
     * Elo Diff Threshold
     */
    elo_diff_threshold?: number;
    /**
     * Iterations
     */
    iterations?: number;
    /**
     * Only Recommended
     */
    only_recommended?: boolean;
  };
  url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}/start_next_round';
};

export type StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostError =
  StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors[keyof StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors];

export type StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses =
  {
    /**
     * Successful Response
     */
    200: SuccessResponse;
  };

export type StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponse =
  StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses[keyof StartNextRoundApiTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses];

export type GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetData =
  {
    body?: never;
    path: {
      /**
       * Tournament Id
       */
      tournament_id: number;
      /**
       * Stage Item Id
       */
      stage_item_id: number;
    };
    query?: {
      /**
       * Elo Diff Threshold
       */
      elo_diff_threshold?: number;
      /**
       * Iterations
       */
      iterations?: number;
      /**
       * Only Recommended
       */
      only_recommended?: boolean;
      /**
       * Limit
       */
      limit?: number;
    };
    url: '/api/tournaments/{tournament_id}/stage_items/{stage_item_id}/upcoming_matches';
  };

export type GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetError =
  GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors[keyof GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors];

export type GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses =
  {
    /**
     * Successful Response
     */
    200: UpcomingMatchesResponse;
  };

export type GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponse =
  GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses[keyof GetMatchesToScheduleApiTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses];

export type GetStagesApiTournamentsTournamentIdStagesGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: {
    /**
     * No Draft Rounds
     */
    no_draft_rounds?: boolean;
  };
  url: '/api/tournaments/{tournament_id}/stages';
};

export type GetStagesApiTournamentsTournamentIdStagesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetStagesApiTournamentsTournamentIdStagesGetError =
  GetStagesApiTournamentsTournamentIdStagesGetErrors[keyof GetStagesApiTournamentsTournamentIdStagesGetErrors];

export type GetStagesApiTournamentsTournamentIdStagesGetResponses = {
  /**
   * Successful Response
   */
  200: StagesWithStageItemsResponse;
};

export type GetStagesApiTournamentsTournamentIdStagesGetResponse =
  GetStagesApiTournamentsTournamentIdStagesGetResponses[keyof GetStagesApiTournamentsTournamentIdStagesGetResponses];

export type CreateStageApiTournamentsTournamentIdStagesPostData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/stages';
};

export type CreateStageApiTournamentsTournamentIdStagesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateStageApiTournamentsTournamentIdStagesPostError =
  CreateStageApiTournamentsTournamentIdStagesPostErrors[keyof CreateStageApiTournamentsTournamentIdStagesPostErrors];

export type CreateStageApiTournamentsTournamentIdStagesPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateStageApiTournamentsTournamentIdStagesPostResponse =
  CreateStageApiTournamentsTournamentIdStagesPostResponses[keyof CreateStageApiTournamentsTournamentIdStagesPostResponses];

export type ActivateNextStageApiTournamentsTournamentIdStagesActivatePostData = {
  body: StageActivateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/stages/activate';
};

export type ActivateNextStageApiTournamentsTournamentIdStagesActivatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ActivateNextStageApiTournamentsTournamentIdStagesActivatePostError =
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostErrors[keyof ActivateNextStageApiTournamentsTournamentIdStagesActivatePostErrors];

export type ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponse =
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponses[keyof ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponses];

export type DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Id
     */
    stage_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/stages/{stage_id}';
};

export type DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteError =
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteErrors[keyof DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteErrors];

export type DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponse =
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponses[keyof DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponses];

export type UpdateStageApiTournamentsTournamentIdStagesStageIdPutData = {
  body: StageUpdateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Id
     */
    stage_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/stages/{stage_id}';
};

export type UpdateStageApiTournamentsTournamentIdStagesStageIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateStageApiTournamentsTournamentIdStagesStageIdPutError =
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutErrors[keyof UpdateStageApiTournamentsTournamentIdStagesStageIdPutErrors];

export type UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponse =
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponses[keyof UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponses];

export type GetTeamsApiTournamentsTournamentIdTeamsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: {
    /**
     * Limit
     *
     * Max number of results in a single page.
     */
    limit?: number;
    /**
     * Offset
     *
     * Filter results starting from this offset.
     */
    offset?: number;
    /**
     * Sort Direction
     */
    sort_direction?: 'asc' | 'desc';
    /**
     * Sort By
     */
    sort_by?:
      | 'name'
      | 'elo_score'
      | 'swiss_score'
      | 'wins'
      | 'draws'
      | 'losses'
      | 'active'
      | 'created';
  };
  url: '/api/tournaments/{tournament_id}/teams';
};

export type GetTeamsApiTournamentsTournamentIdTeamsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTeamsApiTournamentsTournamentIdTeamsGetError =
  GetTeamsApiTournamentsTournamentIdTeamsGetErrors[keyof GetTeamsApiTournamentsTournamentIdTeamsGetErrors];

export type GetTeamsApiTournamentsTournamentIdTeamsGetResponses = {
  /**
   * Successful Response
   */
  200: TeamsWithPlayersResponse;
};

export type GetTeamsApiTournamentsTournamentIdTeamsGetResponse =
  GetTeamsApiTournamentsTournamentIdTeamsGetResponses[keyof GetTeamsApiTournamentsTournamentIdTeamsGetResponses];

export type CreateTeamApiTournamentsTournamentIdTeamsPostData = {
  body: TeamBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/teams';
};

export type CreateTeamApiTournamentsTournamentIdTeamsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTeamApiTournamentsTournamentIdTeamsPostError =
  CreateTeamApiTournamentsTournamentIdTeamsPostErrors[keyof CreateTeamApiTournamentsTournamentIdTeamsPostErrors];

export type CreateTeamApiTournamentsTournamentIdTeamsPostResponses = {
  /**
   * Successful Response
   */
  200: SingleTeamResponse;
};

export type CreateTeamApiTournamentsTournamentIdTeamsPostResponse =
  CreateTeamApiTournamentsTournamentIdTeamsPostResponses[keyof CreateTeamApiTournamentsTournamentIdTeamsPostResponses];

export type DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/teams/{team_id}';
};

export type DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteError =
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteErrors[keyof DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteErrors];

export type DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponse =
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponses[keyof DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponses];

export type UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutData = {
  body: TeamBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/teams/{team_id}';
};

export type UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutError =
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutErrors[keyof UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutErrors];

export type UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponses = {
  /**
   * Successful Response
   */
  200: SingleTeamResponse;
};

export type UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponse =
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponses[keyof UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponses];

export type UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostData = {
  body?: BodyUpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPost;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/teams/{team_id}/logo';
};

export type UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostError =
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostErrors[keyof UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostErrors];

export type UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponses = {
  /**
   * Successful Response
   */
  200: SingleTeamResponse;
};

export type UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponse =
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponses[keyof UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponses];

export type CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostData = {
  body: TeamMultiBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/api/tournaments/{tournament_id}/teams_multi';
};

export type CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostError =
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostErrors[keyof CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostErrors];

export type CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponse =
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponses[keyof CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponses];

export type GetUserApiUsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/users/me';
};

export type GetUserApiUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserPublicResponse;
};

export type GetUserApiUsersMeGetResponse =
  GetUserApiUsersMeGetResponses[keyof GetUserApiUsersMeGetResponses];

export type RegisterUserApiUsersRegisterPostData = {
  body: UserToRegister;
  path?: never;
  query?: never;
  url: '/api/users/register';
};

export type RegisterUserApiUsersRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUserApiUsersRegisterPostError =
  RegisterUserApiUsersRegisterPostErrors[keyof RegisterUserApiUsersRegisterPostErrors];

export type RegisterUserApiUsersRegisterPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type RegisterUserApiUsersRegisterPostResponse =
  RegisterUserApiUsersRegisterPostResponses[keyof RegisterUserApiUsersRegisterPostResponses];

export type RegisterDemoUserApiUsersRegisterDemoPostData = {
  body: DemoUserToRegister;
  path?: never;
  query?: never;
  url: '/api/users/register_demo';
};

export type RegisterDemoUserApiUsersRegisterDemoPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterDemoUserApiUsersRegisterDemoPostError =
  RegisterDemoUserApiUsersRegisterDemoPostErrors[keyof RegisterDemoUserApiUsersRegisterDemoPostErrors];

export type RegisterDemoUserApiUsersRegisterDemoPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type RegisterDemoUserApiUsersRegisterDemoPostResponse =
  RegisterDemoUserApiUsersRegisterDemoPostResponses[keyof RegisterDemoUserApiUsersRegisterDemoPostResponses];

export type GetMeApiUsersUserIdGetData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/api/users/{user_id}';
};

export type GetMeApiUsersUserIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMeApiUsersUserIdGetError =
  GetMeApiUsersUserIdGetErrors[keyof GetMeApiUsersUserIdGetErrors];

export type GetMeApiUsersUserIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserPublicResponse;
};

export type GetMeApiUsersUserIdGetResponse =
  GetMeApiUsersUserIdGetResponses[keyof GetMeApiUsersUserIdGetResponses];

export type UpdateUserDetailsApiUsersUserIdPutData = {
  body: UserToUpdate;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/api/users/{user_id}';
};

export type UpdateUserDetailsApiUsersUserIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserDetailsApiUsersUserIdPutError =
  UpdateUserDetailsApiUsersUserIdPutErrors[keyof UpdateUserDetailsApiUsersUserIdPutErrors];

export type UpdateUserDetailsApiUsersUserIdPutResponses = {
  /**
   * Successful Response
   */
  200: UserPublicResponse;
};

export type UpdateUserDetailsApiUsersUserIdPutResponse =
  UpdateUserDetailsApiUsersUserIdPutResponses[keyof UpdateUserDetailsApiUsersUserIdPutResponses];

export type PutUserPasswordApiUsersUserIdPasswordPutData = {
  body: UserPasswordToUpdate;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/api/users/{user_id}/password';
};

export type PutUserPasswordApiUsersUserIdPasswordPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PutUserPasswordApiUsersUserIdPasswordPutError =
  PutUserPasswordApiUsersUserIdPasswordPutErrors[keyof PutUserPasswordApiUsersUserIdPasswordPutErrors];

export type PutUserPasswordApiUsersUserIdPasswordPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type PutUserPasswordApiUsersUserIdPasswordPutResponse =
  PutUserPasswordApiUsersUserIdPasswordPutResponses[keyof PutUserPasswordApiUsersUserIdPasswordPutResponses];

export type FrontendFullPathGetData = {
  body?: never;
  path: {
    /**
     * Full Path
     */
    full_path: string;
  };
  query?: never;
  url: '/{full_path}';
};

export type FrontendFullPathGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type FrontendFullPathGetError = FrontendFullPathGetErrors[keyof FrontendFullPathGetErrors];

export type FrontendFullPathGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
